### ISSUE TITLE
Environment variable $PASSWORD_STORE_DIR isn't taken into account

### ISSUE THREAD

**Issue by rafi** [cortex/gopass#14]
Password Store features several environment variables for configuration, most notably `PASSWORD_STORE_DIR` allows overriding of the default password storage directory as described in the [man page](https://git.zx2c4.com/password-store/about/#ENVIRONMENT%20VARIABLES). QtPass handles it correctly in [util.cpp](https://github.com/IJHack/qtpass/blob/d930b9d8ed5895fdfe65ea347f59e7eb72667db1/util.cpp#L36) and also takes Windows into account.

**Comment by cortex** [comment]
Thanks for noticing! 
Fixed in https://github.com/cortex/gopass/commit/1585a73880bf8d719b9b44414891ad832c863cac
I didn't know there were special rules for Windows, but now it is implemented anyway =).
