### ISSUE TITLE
Extended clipboard time

### ISSUE THREAD

**Issue by christopherL91** [cortex/gopass#2]
Pass has a default time for items in the clipboard of 45 seconds. Could we handle this though the flag package?

**Comment by cortex** [comment]
Sure, but since this is a GUI, perhaps it would be better to have this as a setting. In any case, using the same default timeout of 45s is likely to surprise less users, so changing the default to that seems like a good idea.

**Comment by christopherL91** [comment]
Cool! I started on building a mac app (just a directory) yesterday and I got it working. I just need to replace my binary with a more static version (the C dependencies)
