### ISSUE TITLE
More key bindings

### ISSUE THREAD

**Issue by jcnoir** [cortex/gopass#9]
Thanks for this nice app. Very handy to use.

It would be nice to have more keybindings : 
- Arrow keys (up, down) to select the right pass in the result list
- Esc to quit the app

**Comment by cortex** [comment]
Added in 19b5cdb24d64b3360c5c98de038b077a175fdb84, please try it out!

**Comment by jcnoir** [comment]
I will !
Thank you very much.

**Comment by jcnoir** [comment]
The new key bindings work fine !

An other idea  : Maybe selecting a password with the enter key should also close the app ? In my use case I always select a password then close the app.
